### ISSUE TITLE
🐍[Travel Agent] module 'travel-concierge' has no attribute 'agent'

### ISSUE THREAD

**Issue by palladius** [google/adk-samples#114]
This error surfaces both in `adk web` and in `adk run` mode:

```
$ adk run travel-concierge/
come va?
Log setup complete: /tmp/agents_log/agent.20250521_121453.log
To access latest log: tail -F /tmp/agents_log/agent.latest.log
Traceback (most recent call last):
  File "/usr/local/google/home/ricc/miniconda3/bin/adk", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/google/adk/cli/cli_tools_click.py", line 78, in cli_run
    asyncio.run(
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ricc/miniconda3/lib/python3.12/site-packages/google/adk/cli/cli.py", line 127, in run_cli
    root_agent = agent_module.agent.root_agent
                 ^^^^^^^^^^^^^^^^^^
AttributeError: module 'travel-concierge' has no attribute 'agent'
```

I'd like to say which adk version i have, but `adk --version` and `adk version` dont work.

**Comment by palladius** [comment]
I have a feeling I'm using adk from version `1.0.0` 

```bash
(.venv) (.venv) (base) ricc@derek:~/git/adk-samples/python/agents$     pip show google-adk | grep Version
Version: 1.0.0
(.venv) (.venv) (base) ricc@derek:~/git/adk-samples/python/agents$ which adk
/usr/local/google/home/ricc/git/adk-samples/python/agents/.venv/bin/adk
```

**Comment by palladius** [comment]
I tested it with both 1.0.0 and 0.5.0 and it seems broken with both.

```justfile
adk-web-100:
    pip install google-adk==1.0.0
    adk web --port 10000
adk-web-050:
    pip install google-adk==0.5.0
    adk web --port 5000
```

Same error. My gist that it was version-dependent seems wrong.

**Comment by gkcng** [comment]
Hi! Thanks for reaching out.

I just retested 0.5.0, both adk run and adk web works with 0.5.0. I am in the middle of migrating to ADK 1.0.0 so watch this space. 

Looking at your error, the issue may be where you are running the commands from. Try runnining the commands while at the directory `adk-samples/python/agents/travel-concierge`, make sure you have a `.env` file setup per README, and the agent is actually `travel_concierge` (underscore instead of dash). 

<img width="1233" alt="Image" src="https://github.com/user-attachments/assets/370fd129-d228-4f97-87fa-478013a4d112" />

```
(travel-concierge-py3.12) ~/adk-samples/python/agents/travel-concierge$ adk run travel_concierge
Log setup complete: /tmp/agents_log/agent.20250522_172954.log
To access latest log: tail -F /tmp/agents_log/agent.latest.log
Running agent root_agent, type exit to exit.
[user]: Hi

Loading Initial State: {'state': {'user_profile': {'passport_nationality': 'US Citizen', 'seat_preference': 'window', 'food_preference': 'vegan', 'allergies': [], 'likes': [], 'dislikes': [], 'price_sensitivity': [], 'home': {'event_type': 'home', 'address': '6420 Sequence Dr #400, San Diego, CA 92121, United States', 'local_prefer_mode': 'drive'}}, 'itinerary': {}, 'origin': '', 'destination': '', 'start_date': '', 'end_date': '', 'outbound_flight_selection': '', 'outbound_seat_number': '', 'return_flight_selection': '', 'return_seat_number': '', 'hotel_selection': '', 'room_selection': '', 'poi': '', 'itinerary_datetime': '', 'itinerary_start_date': '', 'itinerary_end_date': ''}}

[root_agent]: Hi there! How can I help you plan your dream vacation today?

[user]: 
```

**Comment by jainsourabh2** [comment]
@gkcng Can you please help on this?

**Comment by gkcng** [comment]
@jainsourabh2 sounds like you are encountering a different issue entirely to this thread; General ADK Cloud Run deploy issue is best redirect to [the ADK repo](https://github.com/google/adk-python). Thank you!
